# SPDX-License-Identifier: GPL-2.0
#
# Makefile for power sequencer drivers.
#

obj-$(CONFIG_PWRSEQ) += core.o fallback.o

obj-$(CONFIG_PWRSEQ_EMMC)	+= pwrseq_emmc.o
obj-$(CONFIG_PWRSEQ_QCA)	+= pwrseq_qca.o
obj-$(CONFIG_PWRSEQ_SD8787)	+= pwrseq_sd8787.o
obj-$(CONFIG_PWRSEQ_SIMPLE)	+= pwrseq_simple.o
