obj-$(CONFIG_DRM_PANEL_HTC_MEMUL_NOVATEK35521) += panel-htc-memul-novatek35521.o
obj-$(CONFIG_DRM_PANEL_LG_LENOK_LG4237) += panel-lg-lenok-lg4237.o
obj-$(CONFIG_DRM_PANEL_SAMSUNG_MILLETWIFI_S6D7AA0) += panel-samsung-milletwifi-s6d7aa0.o
